$(document).ready(function(){$('#myModal').modal('show');$("#restart").click(function(){location.reload(!0)});var randomNum;var interval;var firstClick=!0;var clickedInput=null;$("#generate").on("click",function(){randomNum=null;$("#result").text('');checkInputs();if(firstClick){interval=setInterval(checkInputs,500);firstClick=!0}});$("input").on("click",function(){var inputValue=$("#result").text();$(this).val(inputValue);clickedInput=$(this)});$("input").keyup(function(){var inputValue=$(this).val();if(inputValue.length===3){var index=$("input").index($(this));$("input").eq(index+1).focus()}});$("input").on("focus",function(){$("#game p").remove()});function checkInputs(){var inputs=[];$("input").each(function(){if($(this).val().length>0){inputs.push(parseInt($(this).val()))}else{inputs.push(null)}});var valid=!0;var invalidInput=null;for(var i=0;i<inputs.length-1;i++){if(inputs[i]!==null&&inputs[i+1]!==null){if(randomNum>inputs[i]&&randomNum<inputs[i+1]){valid=!1;invalidInput=i+1;break}}}
var showAlert=!1;for(var i=inputs.length-1;i>=0;i--){if(inputs[i]!==null){for(var j=i-1;j>=0;j--){if(inputs[j]!==null&&inputs[i]<inputs[j]){alert("Erro: um número maior está abaixo de um campo de entrada com um número menor.");clickedInput.val("");showAlert=!0;break}}
if(showAlert)break}}
if(!showAlert){for(var i=0;i<inputs.length;i++){if(inputs[i]!==null){for(var j=i+1;j<inputs.length;j++){if(inputs[j]!==null&&inputs[i]>inputs[j]){alert("Erro: um número menor está acima de um campo de entrada com um número maior.");clickedInput.val("");showAlert=!0;break}}
if(showAlert)break}}}
if(!randomNum){randomNum=Math.floor(Math.random()*999)+1;var counter=0;var interval=setInterval(function(){var newRandomNum=Math.floor(Math.random()*999)+1;$("#result").text(("000"+newRandomNum).slice(-3));counter++;if(counter===20){clearInterval(interval);$("#result").text(("000"+randomNum).slice(-3))}},100)}
function animateNumber(){var currentNumber=1;var interval=setInterval(function(){$("#result").text(("000"+currentNumber).slice(-3));currentNumber++;if(currentNumber>randomNum){clearInterval(interval);$("#result").text(("000"+randomNum).slice(-3))}},10)}
if(!valid){setTimeout(function(){if(!$("#game p").length){$("#game").append("<p style='color:red'>Você perdeu o jogo! O número gerado não se encaixa entre dois campos consecutivos já preenchidos</p>")}
$("input").off("click");$("input").prop("disabled",!0);$("#generate").hide();$("#restart").show()},3000)}else{$("#game p").remove()}
if(inputs.every(i=>i!==null)){clearInterval(interval);$("#game").append("<p style='color:green'>Parabéns, você ganhou o jogo!</p>");$("input").prop("disabled",!0);$("#generate").hide();$("#restart").show()}}})